name = "CC Vanilla"
author = "CC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "010876da014d642bac269d76389008070411f4b6391cf47671c27fe3df62bd08"

[versions]
minecraft = "1.20.2"
quilt = "0.22.0-beta.1"
