name = "CC Vanilla"
author = "CC"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea85a33ec8be3cdf20e6d37695d549cd9c468287886b31969a6ad8bdd0c26714"

[versions]
minecraft = "1.20.2"
quilt = "0.22.0-beta.1"
